name: CI
on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    permissions:
      contents: read
      checks: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        if: github.event_name == 'pull_request'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: "maven"
      - name: "Run test suite"
        run: mvn clean test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'target/surefire-reports/TEST-*.xml'